### ISSUE TITLE
Does not work with v.3.4.0

### ISSUE THREAD

**Issue by shibulijack-fd** [duizendnegen/ember-cli-lazy-load#13]
Ember version: 3.4.0

Error: Class constructor EmberApp cannot be invoked without 'new'

Stack Trace:
- message: Class constructor EmberApp cannot be invoked without 'new'
  - name: TypeError
  - nodeAnnotation: [undefined]
  - nodeName: [undefined]
  - originalErrorMessage: [undefined]
  - stack: TypeError: Class constructor EmberApp cannot be invoked without 'new'
    at new EmberAppBundle (/Users/shibulijack/Projects/Freshdesk/helpkit-ember/node_modules/ember-cli-lazy-load/ember-app.js:36:14)
    at module.exports (/Users/shibulijack/Projects/Freshdesk/helpkit-ember/ember-cli-build.js:43:13)

**Comment by B-Stefan** [comment]
@shibulijack-fd  Thanks for reporting this bug. 
I will look into this on the weekend.

**Comment by billyjov** [comment]
@B-Stefan any News on upgrade of this package ?
